baseURL = "https://ghveem.github.io/news-feed/"
languageCode = "nn"
title = "MikroNytt"
theme = "hugo-vitae"
paginate = 10
enableRobotsTXT = true


Kode / copyright = "[Panz3r](https://github.com/panz3r) 2021 | [Vitae](https://github.com/panz3r/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
	tag = "tags"

[markup.goldmark.renderer]
  unsafe = true # Optional, allows HTML inside your CommonMark content

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["news","edtech","oer"]

	# Add meta description in head part
	#description = "Mikronytt."

	# Add pagetitle to homepage <title> tag
	pagetitle = "Mikronytt"

	# Add a subtitle to your website
	#subtitle = "[Vitae](https://github.com/dataCobra/hugo-vitae) is a blog theme for Hugo that focuses on your content."

	# Activate to show authors on pages if available
	listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = false

	# Optional 80x80 avatar image.
	#avatar = "/img/vitae.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
  mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Heim"
url = "/"
weight = 1

#[[menu.main]]
#name = "Start"
#url = "/post"
#weight = 2

#[[menu.main]]
#name = "Om"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Emne"
url = "/tags"
weight = 4

#[[menu.main]]
#name = "Kategoriar"
#url = "/categories"
#weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/ghveem/news-feed"

#[[params.social]]
#name = "E-post"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
